# ./docker-compose.yml
# PATH="${PATH}:/usr/local/rvm/gems/ruby-2.3.8/bin"
version: '2'
services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/home/app
      - bundle:/bundle
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    links:
      - mysql
  mysql:
    image: mysql:5.7.18
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
